### ISSUE TITLE
Symlink points to wrong location

### ISSUE THREAD

**Issue by cottsay** [tork-a/euslisp-release#1]
During the install phase, a symlink is created for `euscomp`. This symlink doesn't have the buildroot prefix removed, and so it will be wrong.

It is _highly_ likely that this bug is in the Ubuntu builds as well, but has not been detected.

Example of break: http://csc.mcs.sdsmt.edu/jenkins/job/ros-indigo-euslisp_binaryrpm_heisenbug_i386/50/console

**Comment by k-okada** [comment]
humm, this is strange, 
this symlink is happened here and it seems working under buildroot

```

/builddir/build/BUILD/ros-indigo-euslisp-9.1.0/Linux/obj/comp.o /builddir/build/BUILD/ros-indigo-euslisp-9.1.0/Linux/obj/builtins.l.o  \
    /builddir/build/BUILD/ros-indigo-euslisp-9.1.0/Linux/obj/mthread.o /builddir/build/BUILD/ros-indigo-euslisp-9.1.0/Linux/obj/mthread_posix.o   \
    /builddir/build/BUILD/ros-indigo-euslisp-9.1.0/Linux/obj/par.o \
    -Xlinker -R/builddir/build/BUILD/ros-indigo-euslisp-9.1.0/Linux/lib:/builddir/build/BUILD/ros-indigo-euslisp-9.1.0/lib/Linux -L/builddir/build/BUILD/ros-indigo-euslisp-9.1.0/Linux/lib  -Wl,--no-as-needed -leusx -leusgeo -L/usr/X11R6/lib  -Wl,--no-as-needed -lX11  -ldl -lm -lpthread \
    >/builddir/build/BUILD/ros-indigo-euslisp-9.1.0/Linux/lib/eusmap ; \
cd /builddir/build/BUILD/ros-indigo-euslisp-9.1.0/Linux/bin; rm -f euscomp eusx; \
ln -sf eus euscomp; ln -sf eus eusx; )

```

## 

◉ Kei Okada

**Comment by cottsay** [comment]
I'm sorry, I should have been more precise. I'm not talking about dynamic linking, I'm talking about symbolic file linking.

The link in question is preformed in `Makefile.generic2` [1]. `PUBBINDIR` is set to be `/some/build/root/opt/ros/indigo/bin/`, so the link that is placed on the system points to `/some/build/root/opt/ros/indigo/bin/euscomp` instead of `/opt/ros/indigo/bin/euscomp`.

[1] https://github.com/tork-a/euslisp-release/blob/release/indigo/euslisp/lisp/Makefile.generic2#L359
