### ISSUE TITLE
Build failure on Kinetic build farm

### ISSUE THREAD

**Issue by jackieokay** [tork-a/euslisp-release#10]
euslisp fails to build on Debian Jessie for the arm64 architecture.

http://build.ros.org/job/Kbin_arm_dJv8__euslisp__debian_jessie_arm64__binary/

This platform is less important than Ubuntu amd64 but it would still be good to either fix the issue or disable the package for this platform. Let us know what you prefer.

thanks,

Jackie

**Comment by k-okada** [comment]
https://github.com/ros/rosdistro/pull/11385 should fix the arm64 compile problem.
