### ISSUE TITLE
fails to build for melodic

### ISSUE THREAD

**Issue by dirk-thomas** [tork-a/euslisp-release#16]
The custom logic in this package fails with the recent changes in catkin: ros/catkin/pull/993.

See e.g. http://build.ros.org/view/Mbin_uB64/job/Mbin_uB64__jskeus__ubuntu_bionic_amd64__binary/7/console

**Comment by k-okada** [comment]
@dirk-thomas thanks, #17 should fix this.
btw, are you going to release new catkin to kinetic or lunar? or this is only for melodic?

**Comment by dirk-thomas** [comment]
> are you going to release new catkin to kinetic or lunar? or this is only for melodic?

`catkin` uses the same branch for K, L and M. So at some point the same change will be released into those.

**Comment by k-okada** [comment]
thanks for info!
--
◉ Kei Okada



2019年3月7日(木) 0:19 Dirk Thomas <notifications@github.com>:
