### ISSUE TITLE
Does not build on ARM

### ISSUE THREAD

**Issue by wjwwood** [tork-a/euslisp-release#6]
We're running a test of the new farm and this package continuously fails on ARM with this error:

http://54.183.26.131:8080/job/Jbin_arm_uThf__euslisp__ubuntu_trusty_armhf__binary/8/console

```
23:46:23 (cd c; \
23:46:23     gcc -c -o /tmp/binarydeb/ros-jade-euslisp-9.11.0/LinuxARM/obj/fcall.o  -Darmv6 -DLinux -DARM -D_REENTRANT -DVERSION=\"9.11\" -DLIB6 -falign-functions=4 -g -march=armv6 -DTHREADED -DPTHREAD -DX_V11R6_1 -DGCC -DGCC3 -I/usr/include -I/usr/X11R6/include -I/tmp/binarydeb/ros-jade-euslisp-9.11.0/include fcall.c)
23:46:24 In file included from /usr/include/endian.h:60:0,
23:46:24                  from /usr/include/arm-linux-gnueabihf/bits/waitstatus.h:64,
23:46:24                  from /usr/include/stdlib.h:42,
23:46:24                  from ../c/eus.h:31,
23:46:24                  from fcall.c:9:
23:46:24 /usr/include/arm-linux-gnueabihf/bits/byteswap.h: In function ‘__bswap_32’:
23:46:24 /usr/include/arm-linux-gnueabihf/bits/byteswap.h:45:1: sorry, unimplemented: Thumb-1 hard-float VFP ABI
23:46:24  {
23:46:24  ^
```

See the job here. Please have look into fixing it if possible, but if you cannot I can also disable it on ARM.

**Comment by k-okada** [comment]
@cottsay can you help on this issue?

**Comment by wjwwood** [comment]
Bump, @k-okada if we cannot get this resolved I will disable it for ARM.

**Comment by cottsay** [comment]
I'll try to take a look when I can. At the very least, I can offer SSH access to an ARM slave for @k-okada to debug this, if I can't find time to look into it myself...

**Comment by k-okada** [comment]
hi, I think I fixed this with new release, if it is not, I'd like to try ARM slave access if possible.

**Comment by wjwwood** [comment]
The latest version is segfaulting the q-emu environment. You can keep track of whether or not a build passes by watching the Jenkins farm, new builds are triggered automatically:

http://54.183.26.131:8080/job/Jbin_arm_uThf__euslisp__ubuntu_trusty_armhf__binary/19/console

**Comment by cottsay** [comment]
Looks like the reason this package doesn't build is because drelict isn't available in Fedora on ARM. So I can't be of much help here...

**Comment by wjwwood** [comment]
Well this is the Ubuntu Trusty build, so I figured @k-okada asked you to look at it because you were working together. We're not building Fedora on the test farm yet...

**Comment by k-okada** [comment]
please confirm that it is able to build arm binary, I have been tested on 
https://registry.hub.docker.com/u/mazzolino/armhf-ubuntu/, but it is slightly differnt from orsf osrf/ubuntu_armhf:trusty, installing osrf/ubuntu_arm enable us to reproduce the error and fix them.
